# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("aggreg8.stylesheet.title", "grey");
user_pref("capability.policy.restrictedpopups.Window.open", "allAccess");
user_pref("capability.policy.restrictedpopups.sites", "");
user_pref("dom.disable_open_during_load", true);
user_pref("intl.charset.detector", "universal_charset_detector");
user_pref("keyword.eng", "BBN");
user_pref("keyword.URL", "http://www.google.com/search?gfns=1&q=");
user_pref("kmeleon.MRU.maxURLs", 16);
user_pref("kmeleon.general.guest_account", false);
user_pref("kmeleon.general.homePage", "resource:///readme.html");
user_pref("kmeleon.general.offline", false);
user_pref("kmeleon.general.opengroup", "ID_OPEN_LINK|ID_OPEN_LINK_IN_BACKGROUND");
user_pref("kmeleon.general.openurl", "ID_OPEN_LINK");
user_pref("kmeleon.general.searchEngineName", "Google");
user_pref("kmeleon.general.searchLocked", true);
user_pref("kmeleon.general.skinsCurrent", "Phoenity\\");
user_pref("kmeleon.plugins.bmpmenu.load", true);
user_pref("kmeleon.plugins.bookmarks.chevron", true);
user_pref("kmeleon.plugins.bookmarks.load", false);
user_pref("kmeleon.plugins.bookmarks.menuAutoDetect", true);
user_pref("kmeleon.plugins.bookmarks.openurl", "ID_OPEN_LINK");
user_pref("kmeleon.plugins.external.load", true);
user_pref("kmeleon.plugins.favorites.load", false);
user_pref("kmeleon.plugins.favorites.menuAutoDetect", true);
user_pref("kmeleon.plugins.favorites.openurl", "ID_OPEN_LINK");
user_pref("kmeleon.plugins.fullscreen.load", true);
user_pref("kmeleon.plugins.gestures.down", "layers(OpenLinkBg)");
user_pref("kmeleon.plugins.gestures.downleft", "layers(Last)");
user_pref("kmeleon.plugins.gestures.downright", "layers(Close)");
user_pref("kmeleon.plugins.gestures.left", "ID_NAV_BACK");
user_pref("kmeleon.plugins.gestures.load", true);
user_pref("kmeleon.plugins.gestures.right", "ID_NAV_FORWARD");
user_pref("kmeleon.plugins.gestures.up", "macros(up_directory)");
user_pref("kmeleon.plugins.gestures.upleft", "layers(Prev)");
user_pref("kmeleon.plugins.gestures.upright", "layers(Next)");
user_pref("kmeleon.plugins.history.load", true);
user_pref("kmeleon.plugins.hotlist.load", false);
user_pref("kmeleon.plugins.hotlist.menuAutoDetect", true);
user_pref("kmeleon.plugins.hotlist.openurl", "ID_OPEN_LINK");
user_pref("kmeleon.plugins.layers.confirmClose", true);
user_pref("kmeleon.plugins.layers.load", true);
user_pref("kmeleon.plugins.layers.rebar", true);
user_pref("kmeleon.plugins.layers.style", 2);
user_pref("kmeleon.plugins.macros.load", true);
user_pref("kmeleon.plugins.privacy.load", true);
user_pref("kmeleon.plugins.rebarmenu.load", true);
user_pref("kmeleon.plugins.toolbars.load", true);
user_pref("kmeleon.privacy.useragent0.name", "K-Meleon");
user_pref("kmeleon.privacy.useragent0.string", "");
user_pref("kmeleon.privacy.useragent1.name", "MSIE 6.0");
user_pref("kmeleon.privacy.useragent1.string", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)");
user_pref("kmeleon.privacy.useragent2.name", "Netscape 4.8");
user_pref("kmeleon.privacy.useragent2.string", "Mozilla/4.8 [en] (Windows NT 5.1; U)");
user_pref("kmeleon.privacy.useragent3.name", "Opera 7.54");
user_pref("kmeleon.privacy.useragent3.string", "Opera/7.54 (Windows NT 5.1; U) [en]");
user_pref("kmeleon.toolband.GO.break", 0);
user_pref("kmeleon.toolband.GO.index", 8);
user_pref("kmeleon.toolband.GO.size", 59);
user_pref("kmeleon.toolband.GO.visibility", true);
user_pref("kmeleon.toolband.Layer/Window Buttons.break", 0);
user_pref("kmeleon.toolband.Layer/Window Buttons.index", 1);
user_pref("kmeleon.toolband.Layer/Window Buttons.size", 59);
user_pref("kmeleon.toolband.Layer/Window Buttons.visibility", true);
user_pref("kmeleon.toolband.Layers.visibility", true);
user_pref("kmeleon.toolband.Mail and News.break", 0);
user_pref("kmeleon.toolband.Mail and News.index", 4);
user_pref("kmeleon.toolband.Mail and News.size", 36);
user_pref("kmeleon.toolband.Mail and News.visibility", true);
user_pref("kmeleon.toolband.Main Bar.break", 1);
user_pref("kmeleon.toolband.Main Bar.index", 3);
user_pref("kmeleon.toolband.Main Bar.size", 197);
user_pref("kmeleon.toolband.Main Bar.visibility", true);
user_pref("kmeleon.toolband.Menu.break", 0);
user_pref("kmeleon.toolband.Menu.index", 0);
user_pref("kmeleon.toolband.Menu.size", 933);
user_pref("kmeleon.toolband.Menu.visibility", true);
user_pref("kmeleon.toolband.Privacy Bar.visibility", false);
user_pref("kmeleon.toolband.Search.break", 0);
user_pref("kmeleon.toolband.Search.index", 6);
user_pref("kmeleon.toolband.Search.size", 36);
user_pref("kmeleon.toolband.Search.visibility", true);
user_pref("kmeleon.toolband.Throbber.break", 0);
user_pref("kmeleon.toolband.Throbber.index", 2);
user_pref("kmeleon.toolband.Throbber.size", 28);
user_pref("kmeleon.toolband.Throbber.visibility", true);
user_pref("kmeleon.toolband.URL Bar.break", 0);
user_pref("kmeleon.toolband.URL Bar.index", 7);
user_pref("kmeleon.toolband.URL Bar.size", 536);
user_pref("kmeleon.toolband.URL Bar.visibility", true);
user_pref("kmeleon.toolband.Zoom.break", 0);
user_pref("kmeleon.toolband.Zoom.index", 5);
user_pref("kmeleon.toolband.Zoom.size", 59);
user_pref("kmeleon.toolband.Zoom.visibility", true);
user_pref("network.cookie.cookieBehavior", 0);
