# Mozilla User Preferences
// This is a generated file!

user_pref("kmeleon.plugins.bmpmenu.load", true);
user_pref("kmeleon.plugins.bookmarks.load", true);
user_pref("kmeleon.plugins.external.load", true);
user_pref("kmeleon.plugins.favorites.load", true);
user_pref("kmeleon.plugins.fullscreen.load", true);
user_pref("kmeleon.plugins.history.load", true);
user_pref("kmeleon.plugins.hotlist.load", true);
user_pref("kmeleon.plugins.layers.load", true);
user_pref("kmeleon.plugins.layers.rebar", true);
user_pref("kmeleon.plugins.macros.load", true);
user_pref("kmeleon.plugins.rebarmenu.load", true);
user_pref("kmeleon.plugins.toolbars.load", true);
user_pref("kmeleon.privacy.useragent0.name", "Default");
user_pref("kmeleon.privacy.useragent0.string", "");
user_pref("kmeleon.privacy.useragent1.name", "Netscape 6.1");
user_pref("kmeleon.privacy.useragent1.string", "Mozilla/5.0 (Windows; U; WinNT4.0; en-US) Netscape6/6.1");
user_pref("kmeleon.privacy.useragent2.name", "Netscape 4.76");
user_pref("kmeleon.privacy.useragent2.string", "Mozilla/4.76 [en] (WinNT; U)");
user_pref("kmeleon.privacy.useragent3.name", "MSIE 6.0");
user_pref("kmeleon.privacy.useragent3.string", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)");
user_pref("kmeleon.privacy.useragent4.name", "MSIE 5.5");
user_pref("kmeleon.privacy.useragent4.string", "Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)");
user_pref("kmeleon.privacy.useragent5.name", "MSIE 4.0");
user_pref("kmeleon.privacy.useragent5.string", "Mozilla/4.0 (compatible; MSIE 4.0; Windows NT)");
user_pref("kmeleon.toolband.Bookmarks.break", 1);
user_pref("kmeleon.toolband.Bookmarks.index", 4);
user_pref("kmeleon.toolband.Bookmarks.size", 0);
user_pref("kmeleon.toolband.Bookmarks.visibility", true);
user_pref("kmeleon.toolband.Favorites.break", 1);
user_pref("kmeleon.toolband.Favorites.index", 5);
user_pref("kmeleon.toolband.Favorites.size", 0);
user_pref("kmeleon.toolband.Favorites.visibility", true);
user_pref("kmeleon.toolband.Menu.break", 0);
user_pref("kmeleon.toolband.Menu.index", 0);
user_pref("kmeleon.toolband.Menu.size", 251);
user_pref("kmeleon.toolband.Menu Bar.visibility", true);
user_pref("kmeleon.toolband.Tool Bar.break", 1);
user_pref("kmeleon.toolband.Tool Bar.index", 1);
user_pref("kmeleon.toolband.Tool Bar.size", 175);
user_pref("kmeleon.toolband.Tool Bar.visibility", true);
user_pref("kmeleon.toolband.URL Bar.break", 0);
user_pref("kmeleon.toolband.URL Bar.index", 2);
user_pref("kmeleon.toolband.URL Bar.size", 866);
user_pref("kmeleon.toolband.URL Bar.visibility", true);
user_pref("kmeleon.toolband.layers.break", 1);
user_pref("kmeleon.toolband.layers.index", 4);
user_pref("kmeleon.toolband.layers.size", 771);
user_pref("network.dir.generate_html", true);
