//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MfcEmbed.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_PROMPT_DIALOG               128
#define IDR_MOZEMBTYPE                  129
#define IDD_PROMPT_PASSWORD_DIALOG      129
#define IDR_CTXMENU_DOCUMENT            130
#define IDD_PROMPT_USERPASS_DIALOG      130
#define IDR_CTXMENU_LINK                131
#define IDD_ALERT_CHECK_DIALOG          131
#define IDR_CTXMENU_TEXT                132
#define IDD_CONFIRM_CHECK_DIALOG        132
#define IDR_CTXMENU_IMAGE               133
#define IDD_SEARCH_DIALOG               134
#define IDD_PROFILES                    137
#define IDD_PROFILE_NEW                 138
#define IDD_PROFILE_RENAME              139
#define IDD_FINDDLG                     140
#define IDB_TOOLBAR_HOT                 143
#define IDB_TOOLBAR_COLD                144
#define IDR_MFCAVI                      145
#define IDB_BACK                        147
#define IDI_ICON1                       150
#define IDB_TOOLBAR_DISABLED            151
#define IDR_MENU_TEXT                   152
#define IDD_PREFERENCES                 154
#define IDD_PREFERENCES_DISPLAY         155
#define IDD_PREFERENCES_PROXY           156
#define IDD_PREFERENCES_GENERAL         157
#define IDI_DOCUMENT                    157
#define IDD_PREFERENCES_PLUGINS         158
#define IDD_PREFERENCES_ADVANCED        159
#define IDC_PAN_DOWN                    160
#define IDD_PREFERENCES_MENUS           160
#define IDD_PREFERENCES_CONFIGS         160
#define IDC_PAN_UP                      161
#define IDD_PREFERENCES_CACHE           161
#define IDD_ERRORBOX                    162
#define IDD_PREFERENCES_MOZCONFIGS      163
#define IDC_PAN_RIGHT                   163
#define IDC_PAN_LEFT                    164
#define IDC_PAN                         165
#define IDC_PAN_UPLEFT                  166
#define IDC_PAN_DOWNLEFT                167
#define IDC_PAN_UPRIGHT                 168
#define IDC_PAN_DOWNRIGHT               169
#define IDD_PRINT_PROGRESS_DIALOG       170
#define IDI_ON                          175
#define IDI_OFF                         176
#define IDI_OFFCHECK                    179
#define IDI_ONCHECK                     180
#define IDD_DIALOG_OPEN                 181
#define IDD_PROGRESS                    182
#define IDR_SECURITY_LOCK               183
#define IDD_PREFERENCES_PRIVACY         183
#define IDR_SECURITY_UNLOCK             184
#define IDD_PREFERENCES_LANGUAGE        184
#define IDR_SECURITY_BROKEN             185
#define IDS_ENCRYPTION_HIGH_GRADE       187
#define IDS_ENCRYPTION_LOW_GRADE        188
#define IDS_ENCRYPTION_NONE             189
#define IDD_FILE_PRINTSETUP             190
#define IDD_PRINTSETUP_DIALOG           191
#define IDD_CHOOSE_ACTION_DIALOG        192
#define ID_URL_BAR                      1001
#define ID_PROG_BAR                     1002
#define ID_THROBBER                     1003
#define IDC_PROMPT_ANSWER               1003
#define IDC_SEARCH_QUERY                1003
#define IDC_PROMPT_QUESTION             1004
#define IDC_PROMPT_TEXT                 1005
#define IDC_USERNAME                    1006
#define IDC_PASSWORD                    1007
#define IDC_CHECK_SAVE_PASSWORD         1008
#define IDC_CHECKBOX                    1008
#define IDC_USERNAME_LABEL              1009
#define IDC_MSG_TEXT                    1009
#define IDC_PASSWORD_LABEL              1010
#define IDC_BTN1                        1010
#define IDC_LIST1                       1011
#define IDC_BTN2                        1011
#define IDC_PROF_RENAME                 1012
#define IDC_BTN3                        1012
#define IDC_PROF_DELETE                 1013
#define IDC_PROF_NEW                    1014
#define IDC_CHECK_ASK_AT_START          1015
#define IDC_NEW_PROF_NAME               1016
#define IDC_CONTENT_TYPE                1016
#define IDC_LOCALE_COMBO                1017
#define IDC_SAVE_TO_DISK                1017
#define IDC_NEW_NAME                    1018
#define IDC_OPEN_USING                  1018
#define IDC_CREDITS                     1019
#define IDC_CHOOSE_APP                  1019
#define IDC_PPD_DOC_TXT                 1020
#define IDC_APP_NAME                    1020
#define IDC_EDIT_HTTP_PROXY_PORT        1021
#define IDC_PPD_DOC_TITLE_STATIC        1021
#define IDC_CHECK_PROXY_TYPE            1022
#define IDC_EDIT_PROXY_NO_PROXY         1023
#define IDC_CHECK_JAVASCRIPT            1024
#define IDC_EDIT_FTP_PROXY_PORT         1024
#define IDC_CHECK_COOKIES               1025
#define IDC_EDIT_SSL_PROXY_PORT         1025
#define IDC_CHECK_IMAGES                1026
#define IDC_EDIT_GOPHER_PROXY_PORT      1026
#define IDC_CHECK_JAVA                  1027
#define IDC_EDIT_SOCKS_PROXY_PORT       1027
#define IDC_IMAGES_ALL                  1030
#define IDC_CHECK_ANIMATIONS            1031
#define IDC_IMAGES_SITE                 1032
#define IDC_PAPER_SIZE_CBX              1032
#define IDC_EDIT1                       1033
#define IDC_IMAGES_NONE                 1033
#define IDC_UD_PAPER_HGT                1033
#define IDC_EDIT_DISK_CACHE             1034
#define IDC_COOKIES_ALL                 1034
#define IDC_UD_PAPER_WDTH               1034
#define IDC_BUTTON_MENUS                1035
#define IDC_EDIT_CACHE_DIRECTORY        1035
#define IDC_COOKIES_SITE                1035
#define IDC_UD_WIDTH_LBL                1035
#define IDC_BUTTON_ACCEL                1036
#define IDC_COOKIES_NONE                1036
#define IDC_UD_HEIGHT_LBL               1036
#define IDC_BUTTON_HELP                 1037
#define IDC_INCHES_RD                   1037
#define IDC_COMBO_USERAGENT             1038
#define IDC_COMBO                       1038
#define IDC_MILLI_RD                    1038
#define IDC_RADIO_CURRENT               1039
#define IDC_HDR_LEFT_TXT                1039
#define IDC_MATCH_WHOLE_WORD            1040
#define IDC_RADIO_HOME                  1040
#define IDC_HDR_MID_TXT                 1040
#define IDC_MATCH_CASE                  1041
#define IDC_RADIO_URL                   1041
#define IDC_HDR_RIGHT_TXT               1041
#define IDC_WRAP_AROUND                 1042
#define IDC_FTR_LEFT_TXT                1042
#define IDC_SEARCH_BACKWARDS            1043
#define IDC_DOWNLOAD_PROGRESS           1043
#define IDC_FTR_MID_TXT                 1043
#define IDC_DESTINATION                 1044
#define IDC_FTR_RIGHT_TXT               1044
#define IDC_STATUS                      1045
#define IDC_SOURCE                      1046
#define IDC_TIME_LEFT                   1047
#define IDC_CHECK_SOURCE_ENABLED        1050
#define IDC_RADIO_ONCE                  1050
#define IDC_SPEED                       1050
#define IDC_RADIO_ONCE1                 1050
#define IDC_EDIT_SOURCE_COMMAND         1051
#define IDC_RADIO_ALWAYS                1051
#define IDC_CLOSE_WHEN_DONE             1051
#define IDC_RADIO_NEVER                 1052
#define IDC_OPEN                        1052
#define IDC_CHECK1                      1053
#define IDC_RADIO_AUTO                  1053
#define IDC_CHECK_LOAD                  1053
#define IDC_CHECK_PASSWORDS             1053
#define IDC_BUTTON2                     1054
#define IDC_RADIO1                      1054
#define IDC_RADIO_CACHE                 1054
#define IDC_RADIO_NEWWINDOW             1054
#define IDC_EDIT_ADDRESS                1055
#define IDC_BUTTON3                     1055
#define IDC_RADIO2                      1055
#define IDC_PROMPT_ADDRESS_TEXT         1056
#define IDC_EDIT_MEMORY_CACHE           1056
#define IDC_CHECK_RESTRICT              1056
#define IDC_RADIO3                      1057
#define IDC_EDIT_HTTP                   1057
#define IDC_ERRORS                      1058
#define IDC_RADIO4                      1058
#define IDC_EDIT_RESTRICT               1058
#define IDC_VERSION                     1059
#define IDC_EDIT_USERAGENT              1060
#define IDC_TAB1                        1063
#define IDC_BUTTON1                     1064
#define IDC_BUTTON_CLEAR_MEM_CACHE      1065
#define IDC_RADIO5                      1066
#define IDC_EDIT_PROXY_AUTO             1068
#define IDC_RADIO_SOCKS                 1069
#define IDC_RADIO_PROXY                 1070
#define IDC_RADIO7                      1071
#define IDC_RADIO8                      1072
#define IDC_BUTTON_COOKIES              1073
#define IDC_COMBO1                      1074
#define IDC_COMBO2                      1075
#define IDC_BUTTON_CLEAR_DISK_CACHE     1076
#define IDC_CHECK_DISABLERESIZE         1077
#define IDC_COMBO_SKIN                  1078
#define IDC_CONTAINER                   1110
#define IDC_EDIT_TOOLBAR_BACKGROUND     1111
#define IDC_EDIT_SETTINGS_DIR           1111
#define IDC_RADIO_START_HOME            1112
#define IDC_RADIO_START_BLANK           1113
#define IDC_EDIT_HOMEPAGE               1114
#define IDC_EDIT_PROXY                  1115
#define IDC_EDIT_HTTP_PROXY             1115
#define IDC_EDIT_PLUGINS_DIR            1115
#define IDC_CHECK_TOOLBAR_BACKGROUND    1116
#define IDC_EDIT_FTP_PROXY              1116
#define IDC_BUTTON_BROWSE               1117
#define IDC_EDIT_SSL_PROXY              1117
#define IDC_LIST_PLUGINS                1118
#define IDC_EDIT_GOPHER_PROXY           1118
#define IDC_BUTTON_CONFIG               1119
#define IDC_EDIT_SOCKS_PROXY            1119
#define IDC_KMELEON_HOME                1120
#define IDC_BUTTON_ENABLE               1120
#define IDC_KMELEON_FORUM               1121
#define IDC_EDIT_URL                    1122
#define IDC_LEFT_MARGIN_TXT             1123
#define IDC_TOP_MARGIN_TXT              1124
#define IDC_BOTTOM_MARGIN_TXT           1125
#define IDC_RIGHT_MARGIN_TXT            1126
#define IDC_PRT_BGCOLORS                1127
#define IDC_SCALE                       1128
#define IDC_SCALE_TXT                   1129
#define IDC_PRT_BGIMAGES                1130
#define IDC_FIND_EDIT                   1152
#define ID_NAV_BACK                     32773
#define ID_NAV_FORWARD                  32774
#define ID_NAV_HOME                     32775
#define ID_NAV_STOP                     32776
#define ID_NAV_RELOAD                   32777
#define ID_NAV_SEARCH                   32778
#define ID_EDIT_SELECT_NONE             32781
#define ID_NEW_BROWSER                  32782
#define ID_VIEW_SOURCE                  32783
#define ID_VIEW_INFO                    32784
#define ID_VIEW_IMAGE                   32785
#define ID_OPEN_LINK_IN_NEW_WINDOW      32786
#define ID_SAVE_LINK_AS                 32787
#define ID_SAVE_IMAGE_AS                32788
#define ID_COPY_LINK_LOCATION           32789
#define ID_PREFERENCES                  32790
#define ID_SELECT_URL                   32791
#define ID_MANAGE_PROFILES              32792
#define ID_COPY_IMAGE_LOCATION          32793
#define ID_LINK_KMELEON_HOME            32794
#define ID_LINK_KMELEON_FORUM           32795
#define ID_EDIT_FINDNEXT                32796
#define ID_EDIT_FINDPREV                32797
#define ID_OPEN_LINK_IN_BACKGROUND      32798
#define ID_WINDOW_NEXT                  32799
#define ID_WINDOW_PREV                  32800
#define ID_FILE_PRINTPREVIEW            32801
#define ID_FILE_PRINTSETUP              32802
#define ID_TOOLBARS_LOCK                32803
#define ID_VIEW_FRAME_SOURCE            32804
#define ID_OPEN_FRAME_IN_NEW_WINDOW     32805
#define ID_OPEN_LINK                    32806
#define ID_OPEN_FRAME                   32807
#define ID_OPEN_FRAME_IN_BACKGROUND     32808
#define ID_FONT_INCREASE                32809
#define ID_FONT_DECREASE                32810
#define ID_LINK_KMELEON_FAQ             32811
#define ID_LINK_KMELEON_MANUAL          32812
#define ID_LINK_ABOUT_PLUGINS           32813
#define ID_NAV_FORCE_RELOAD             32814
#define ID_FILE_SAVE_FRAME_AS           32815
#define ID_VIEW_PAGE_INFO               32816
#define ID_VIEW_FRAME_INFO              32817
#define ID_MOUSE_ACTION                 32818
#define ID_NAV_GO                       32819
#define ID_OFFLINE                      32820
#define ID_COPY_IMAGE_CONTENT           32821
#define IDS_FAILED_TO_CREATE_BROWSER    61204
#define IDS_NEW_PLUGIN_FOUND            61205
#define IDS_PLUGIN_NO_OPTIONS           61206
#define IDS_PLUGIN_NOT_LOADED           61207
#define IDS_PROFILE_EXISTS              61208
#define IDS_PROFILE_BAD_CHARS           61209
#define IDS_DOWNLOAD_DONE               61210
#define IDS_DOWNLOAD_PROGRESS           61211
#define IDS_TIMELEFT_HOURS              61212
#define IDS_TIMELEFT_SECONDS            61213
#define IDS_TIMELEFT_MINUTES            61214
#define IDS_TIMELEFT_MINUTE             61215
#define IDS_PERCENT_OF_FILE             61216
#define IDS_PROFILE_SWITCH              61217
#define IDS_OLD_PLUGIN                  61218
#define IDS_DOWNLOAD_PROGRESS2          61219
#define IDS_UNABLE_REGISTER_FACTORY     61228
#define IDS_NOSECURITY_INFO             61220
#define IDS_SPEED_STRING                61221
#define IDS_REDIRECTING                 61222
#define IDS_DOWNLOADING                 61223
#define IDS_NEGOTIATING                 61224
#define IDS_CONTACTING                  61225
#define IDS_SAVE_CHANGES                61226
#define IDS_ERROR_OPEN                  61227
#define IDS_CLOSE                       61229
#define IDS_TIMELEFT_UNKNOWN            61230
#define IDS_PREFS_GENERAL               61244
#define IDS_PREFS_DISPLAY               61245
#define IDS_PREFS_PRIVACY               61246
#define IDS_PREFS_CACHE                 61247
#define IDS_PREFS_PROXY                 61248
#define IDS_PREFS_CONFIGS               61249
#define IDS_PREFS_PLUGINS               61250
#define IDS_DOWNLOAD_FAILED             61254

#define IDD_CONFIRM_COOKIE              2100
#define IDC_CHECK_REMEMBER              2101
#define IDOKSESSION                     2104
#define IDALLOWSESSION                  2104
#define IDALLOW                         2105
#define IDDENY                          2106
#define IDC_COOKIE_NAME                 2107
#define IDC_COOKIE_VALUE                2108
#define IDC_COOKIE_HOST                 2109
#define IDC_COOKIE_PATH                 2110
#define IDC_COOKIE_SENDFOR              2111
#define IDC_COOKIE_EXPIRES              2112
#define IDC_COOKIE_ICON                 2115
#define IDC_COOKIE_TEXT                 2116
#define IDC_COOKIE_NAME2                2117
#define IDS_COOKIE_MODIFY               5000
#define IDS_COOKIE_SET                  5001
#define IDS_COOKIE_SET2                 5002
#define IDS_COOKIE_ANOTHER              5003
#define IDS_FOR_SECURE                  5004
#define IDS_FOR_ANY                     5005
#define IDS_ESPIRES_EOS                 5006

#define IDD_NEWSERVER                   9
#define IDD_DIALOG1                     104
#define IDD_DOMAIN_MISMATCH             104
#define IDD_SERVERCRLNEXTUPDATE         106
#define IDD_DOWNLOAD_CERT               108
#define IDD_SETPKCS12FILEPASSWORD       110
#define IDD_GETPKCS12FILEPASSWORD       111
#define IDD_VIEWCERT_GENERAL            112
#define IDD_VIEW_CERT_DETAILS           115
#define IDD_CONFIRM_EXPIRED_CERT        2000
#define IDC_VIEW_CERT                   2002
#define IDC_HELP_CERT                   2004
#define IDC_STATIC_MSG                  2006
#define IDC_STATIC_CORRECTIME           2007
#define IDC_REASON3                     2010
#define IDC_INTRO                       2011
#define IDC_QUESTION                    2014
#define IDC_REMEMBER                    2016
#define IDC_SESSION                     2017
#define IDC_REFUSE                      2018
#define IDC_MSG1                        2020
#define IDC_MSG2                        2021
#define IDC_CHECKSSL                    2022
#define IDC_CHECKEMAIL                  2023
#define IDC_CHECKOBJSIGN                2024
#define IDC_PWD1                        2026
#define IDC_PWD2                        2027
#define IDC_PWD_QUALITY                 2028
#define IDC_EDIT_CN                     2030
#define IDC_EDIT_O2                     2031
#define IDC_EDIT_O                      2032
#define IDC_EDIT_OU                     2033
#define IDC_EDIT_SN                     2034
#define IDC_EDIT_OU2                    2035
#define IDC_EDIT_CN2                    2036
#define IDC_EXPIRES_DATE                2037
#define IDC_ISSUED_DATE                 2038
#define IDC_MD5                         2039
#define IDC_SHA1                        2040
#define IDC_VERIFIED                    2044
#define IDC_USAGE                       2045
#define IDC_CERT_FIELDS                 2051
#define IDC_CERT_HIERARCHY              2052
#define IDC_FIELD_VALUE                 2053
#define IDS_CERTEXPIREDTITLE            5100
#define IDS_CERTNOTVALIDTITLE           5101
#define IDS_CERTEXPIREDMSG              5102
#define IDS_CERTNOTVALIDMSG             5103
#define IDS_CORRECT_COMPUTER_TIME       5104
#define IDS_NEWSERVER_INTRO             5105
#define IDS_NEWSERVER_REASON3           5106
#define IDS_NEWSERVER_QUESTION          5107
#define IDS_mismatchDomainMsg1          5108
#define IDS_STRING5109                  5109
#define IDS_mismatchDomainMsg2          5109
#define IDS_crlNextUpdateMsg1           5110
#define IDS_crlNextUpdateMsg2           5111
#define IDS_crlNextUpdateMsg3           5112
#define IDS_newCAMessage1               5113
#define IDS_CERTEXISTS                  5114
#define IDS_CERT_VERIFIED_OK            5115
#define IDS_CERT_REVOKED                5116
#define IDS_CERT_EXPIRED                5117
#define IDS_CERT_NOT_TRUSTED            5118
#define IDS_CERT_ISSUER_NOT_TRUSTED     5119
#define IDS_CERT_ISSUER_UNKNOWN         5120
#define IDS_CERT_INVALID_CA             5121
#define IDS_CERT_NOT_VERIFIED_UNKNOWN   5122
#define IDS_CERT_VIEWER_TITLE           5123
#define IDS_DATE_FORMAT                 5124
#define IDS_PASSWORD_MISMATCH           5125

#define IDD_DOWNLOADFONT                102
#define IDD_NEEDFONT                    103
#define IDC_FONTSPEC                    1002
#define IDC_FONTNAME                    1003
#define IDC_FONTSIZE                    1004
#define IDS_HANDLED_LANGUAGES           5200
#define IDS_NAME_FIRST                  5201
#define IDS_NAME_ja                     5201
#define IDS_NAME_ko                     5202
#define IDS_NAME_zh_cn                  5203
#define IDS_NAME_zh_tw                  5204
#define IDS_SIZE_FIRST                  5250
#define IDS_SIZE_ja                     5250
#define IDS_SIZE_ko                     5251
#define IDS_SIZE_zh_cn                  5252
#define IDS_SIZE_zh_tw                  5253
#define IDS_NAME_UNKNOW                 5280

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
