//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by KMeleon.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_BCGIEDTYPE                  129
#define IDR_MAINFRAME2                  129
#define IDR_POPUP_TOOLBAR               131
#define IDR_FONT_POPUP                  132
#define IDR_MFCAVI                      132
#define IDR_FAVORITES_POPUP             133
#define IDB_LOGO                        133
#define IDR_HISTORY_POPUP               134
#define IDB_MENU_IMAGES                 134
#define IDB_BACK                        135
#define IDB_COLDTOOLBAR_SMALL           136
#define IDB_HOTTOOLBAR_SMALL            137
#define IDC_PAN_DOWN                    140
#define IDC_PAN_UP                      141
#define IDC_PAN_RIGHT                   143
#define IDC_PAN_LEFT                    144
#define IDC_PAN                         145
#define IDC_PAN_UPLEFT                  146
#define IDC_PAN_DOWNLEFT                147
#define IDC_PAN_UPRIGHT                 148
#define IDC_PAN_DOWNRIGHT               149
#define IDR_BROWSER_POPUP               150
#define IDR_LINK_POPUP                  151
#define IDD_PROMPT                      152
#define IDD_PROMPT_USERNAME_PASSWORD    153
#define IDD_PREFERENCES                 154
#define IDD_PREFERENCES_DISPLAY         155
#define IDD_PREFERENCES_PROXY           156
#define IDD_PREFERENCES_GENERAL         157
#define IDD_PREFERENCES_PLUGINS         158
#define IDB_COLDTOOLBAR                 261
#define IDB_HOTTOOLBAR                  262
#define IDS_WEB_TUTORIAL                736
#define IDS_ONLINE_SUPPORT              737
#define IDS_FREE_STUFF                  738
#define IDS_GET_FASTER_INTERNET_ACCESS  741
#define IDS_FREQUENTLY_ASKED_QUESTIONS  742
#define IDS_INTERNET_START_PAGE         743
#define IDS_SEND_FEEDBACK               744
#define IDS_BEST_OF_THE_WEB             745
#define IDS_SEARCH_THE_WEB              746
#define IDS_MICROSOFT_HOME_PAGE         747
#define IDS_BACK                        748
#define IDS_FORWARD                     749
#define IDS_STOP                        750
#define IDS_REFRESH                     751
#define IDS_HOME                        752
#define IDS_SEARCH                      753
#define IDS_FAVORITES                   754
#define IDS_PRINT                       755
#define IDS_FONT                        756
#define IDS_ADDRESS                     757
#define IDS_LINKS                       758
#define IDC_MAIL                        1000
#define IDC_URL                         1001
#define IDC_VERSION                     1002
#define IDC_URL_GECKO                   1002
#define IDC_URL_BCG                     1003
#define IDC_EDITBOX                     1003
#define IDC_CAPTION                     1004
#define IDC_EDIT_USERNAME               1005
#define IDC_EDIT_PASSWORD               1006
#define IDC_LIST1                       1009
#define IDC_CONTAINER                   1010
#define IDC_EDIT1                       1011
#define IDC_EDIT_TOOLBAR_BACKGROUND     1011
#define IDC_RADIO_START_HOME            1012
#define IDC_RADIO_START_BLANK           1013
#define IDC_EDIT_HOMEPAGE               1014
#define IDC_EDIT_PROXY                  1015
#define IDC_CHECK_TOOLBAR_BACKGROUND    1016
#define IDC_BUTTON_BROWSE               1017
#define IDC_LIST_PLUGINS                1018
#define IDC_BUTTON_CONFIG               1019
#define IDS_FILETYPES                   1201
#define ID_VIEW_ADDRESS_BAR             32722
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_STOP                    32778
#define ID_VIEW_REFRESH                 32779
#define ID_LINK_1                       32781
#define ID_VIEW_FONTS_LARGEST           32782
#define ID_VIEW_FONTS_LARGE             32783
#define ID_VIEW_FONTS_MEDIUM            32784
#define ID_VIEW_FONTS_SMALL             32785
#define ID_VIEW_FONTS_SMALLEST          32786
#define ID_GO_BACK                      32787
#define ID_GO_FORWARD                   32788
#define ID_GO_START_PAGE                32789
#define ID_GO_SEARCH_THE_WEB            32790
#define ID_GO_BEST_OF_THE_WEB           32791
#define ID_FAVORITES_DROPDOWN           32792
#define ID_FONT_DROPDOWN                32793
#define ID_HELP_WEB_TUTORIAL            32798
#define ID_HELP_ONLINE_SUPPORT          32800
#define ID_HELP_MICROSOFT_ON_THE_WEB_FREE_STUFF 32801
#define ID_HELP_MICROSOFT_ON_THE_WEB_GET_FASTER_INTERNET_ACCESS 32802
#define ID_HELP_MICROSOFT_ON_THE_WEB_FREQUENTLY_ASKED_QUESTIONS 32803
#define ID_HELP_MICROSOFT_ON_THE_WEB_SEND_FEEDBACK 32804
#define ID_HELP_MICROSOFT_ON_THE_WEB_BEST_OF_THE_WEB 32805
#define ID_HELP_MICROSOFT_ON_THE_WEB_SEARCH_THE_WEB 32806
#define ID_HELP_MICROSOFT_ON_THE_WEB_MICROSOFT_HOME_PAGE 32807
#define ID_HELP_MICROSOFT_ON_THE_WEB_INTERNET_START_PAGE 32812
#define ID_FAVORITS_DUMMY               32819
#define ID_HISTORY_DUMMY                32820
#define ID_VIEW_LINKS_BAR               32821
#define ID_VIEW_TEXTLABELS              32823
#define ID_VIEW_BACKGROUND              32824
#define ID_FILE_NEWWINDOW               32825
#define ID_HELP_WEB_KMELEON_HOME        32826
#define ID_HELP_WEB_KMELEON_FORUM       32827
#define ID_POPUP_OPEN                   32830
#define ID_POPUP_OPENINANEWWINDOW       32831
#define ID_POPUP_COPYSHORTCUT           32832
#define ID_VIEW_SOURCE                  32834
#define ID_PREFERENCES                  32835
#define ID_VIEW_PREFERENCES             32836

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32837
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
