/* Weditres generated include file. Do NOT edit */
#define	DLG_CONFIG	100
#define	CHK_COOKIES_STARTUP	102
#define	BTN_CLEAR_COOKIES	103
#define	CHK_COOKIES_SHUTDOWN	104
#define	CHK_CACHE_STARTUP	106
#define	BTN_CLEAR_CACHE	107
#define	CHK_CACHE_SHUTDOWN	108
#define	CHK_MRU_STARTUP	110
#define	BTN_CLEAR_MRU	111
#define	CHK_MRU_SHUTDOWN	112
#define	CHK_SIGNON_STARTUP	114
#define	BTN_CLEAR_SIGNON	115
#define	CHK_SIGNON_SHUTDOWN	116
#define	CHK_HISTORY_STARTUP	118
#define	BTN_CLEAR_HISTORY	119
#define	CHK_HISTORY_SHUTDOWN	120
