user_pref("kmeleon.toolband.&Go Buttons.break", 0);
user_pref("kmeleon.toolband.&Go Buttons.index", 5);
user_pref("kmeleon.toolband.&Go Buttons.size", 59);
user_pref("kmeleon.toolband.&Go Buttons.visibility", true);
user_pref("kmeleon.toolband.&Main Bar.break", 1);
user_pref("kmeleon.toolband.&Main Bar.index", 2);
user_pref("kmeleon.toolband.&Main Bar.size", 197);
user_pref("kmeleon.toolband.&Main Bar.visibility", true);
user_pref("kmeleon.toolband.&Privacy Bar.break", 1);
user_pref("kmeleon.toolband.&Privacy Bar.index", 9);
user_pref("kmeleon.toolband.&Privacy Bar.size", 2000);
user_pref("kmeleon.toolband.&Privacy Bar.visibility", false);
user_pref("kmeleon.toolband.&Search Buttons.break", 0);
user_pref("kmeleon.toolband.&Search Buttons.index", 4);
user_pref("kmeleon.toolband.&Search Buttons.size", 36);
user_pref("kmeleon.toolband.&Search Buttons.visibility", false);
user_pref("kmeleon.toolband.&Zoom Buttons.break", 0);
user_pref("kmeleon.toolband.&Zoom Buttons.index", 7);
user_pref("kmeleon.toolband.&Zoom Buttons.size", 59);
user_pref("kmeleon.toolband.&Zoom Buttons.visibility", false);
user_pref("kmeleon.toolband.Bookmarks.break", 1);
user_pref("kmeleon.toolband.Bookmarks.index", 10);
user_pref("kmeleon.toolband.Bookmarks.size", 79);
user_pref("kmeleon.toolband.Bookmarks.visibility", false);
user_pref("kmeleon.toolband.Mail/&News Buttons.break", 0);
user_pref("kmeleon.toolband.Mail/&News Buttons.index", 8);
user_pref("kmeleon.toolband.Mail/&News Buttons.size", 36);
user_pref("kmeleon.toolband.Mail/&News Buttons.visibility", false);
user_pref("kmeleon.toolband.Menu.break", 0);
user_pref("kmeleon.toolband.Menu.index", 0);
user_pref("kmeleon.toolband.Menu.size", 510);
user_pref("kmeleon.toolband.Menu.visibility", true);
user_pref("kmeleon.toolband.Tab/&Window Buttons.break", 0);
user_pref("kmeleon.toolband.Tab/&Window Buttons.index", 6);
user_pref("kmeleon.toolband.Tab/&Window Buttons.size", 59);
user_pref("kmeleon.toolband.Tab/&Window Buttons.visibility", true);
user_pref("kmeleon.toolband.Tabs.break", 1);
user_pref("kmeleon.toolband.Tabs.index", 14);
user_pref("kmeleon.toolband.Tabs.size", 2000);
user_pref("kmeleon.toolband.Tabs.visibility", true);
user_pref("kmeleon.toolband.Throbber.break", 0);
user_pref("kmeleon.toolband.Throbber.index", 1);
user_pref("kmeleon.toolband.Throbber.size", 28);
user_pref("kmeleon.toolband.Throbber.visibility", true);
user_pref("kmeleon.toolband.URL Bar.break", 0);
user_pref("kmeleon.toolband.URL Bar.index", 3);
user_pref("kmeleon.toolband.URL Bar.size", 2000);
user_pref("kmeleon.toolband.URL Bar.visibility", true);