//Default Toolbar position for Phoenity

pref("kmeleon.toolband.&Go Buttons.break", 0);
pref("kmeleon.toolband.&Go Buttons.index", 8);
pref("kmeleon.toolband.&Go Buttons.size", 59);
pref("kmeleon.toolband.&Go Buttons.visibility", true);
pref("kmeleon.toolband.Layer/&Window Buttons.break", 0);
pref("kmeleon.toolband.Layer/&Window Buttons.index", 1);
pref("kmeleon.toolband.Layer/&Window Buttons.size", 59);
pref("kmeleon.toolband.Layer/&Window Buttons.visibility", true);
pref("kmeleon.toolband.Layers.visibility", true);
pref("kmeleon.toolband.Mail/&News Buttons.break", 0);
pref("kmeleon.toolband.Mail/&News Buttons.index", 4);
pref("kmeleon.toolband.Mail/&News Buttons.size", 36);
pref("kmeleon.toolband.Mail/&News Buttons.visibility", true);
pref("kmeleon.toolband.&Main Bar.break", 1);
pref("kmeleon.toolband.&Main Bar.index", 3);
pref("kmeleon.toolband.&Main Bar.size", 197);
pref("kmeleon.toolband.&Main Bar.visibility", true);
pref("kmeleon.toolband.Menu.break", 0);
pref("kmeleon.toolband.Menu.index", 0);
pref("kmeleon.toolband.Menu.size", 933);
pref("kmeleon.toolband.Menu.visibility", true);
pref("kmeleon.toolband.&Privacy Bar.visibility", false);
pref("kmeleon.toolband.&Search Buttons.break", 0);
pref("kmeleon.toolband.&Search Buttons.index", 6);
pref("kmeleon.toolband.&Search Buttons.size", 36);
pref("kmeleon.toolband.&Search Buttons.visibility", true);
pref("kmeleon.toolband.Throbber.break", 0);
pref("kmeleon.toolband.Throbber.index", 2);
pref("kmeleon.toolband.Throbber.size", 28);
pref("kmeleon.toolband.Throbber.visibility", true);
pref("kmeleon.toolband.URL Bar.break", 0);
pref("kmeleon.toolband.URL Bar.index", 7);
pref("kmeleon.toolband.URL Bar.size", 536);
pref("kmeleon.toolband.URL Bar.visibility", true);
pref("kmeleon.toolband.&Zoom Buttons.break", 0);
pref("kmeleon.toolband.&Zoom Buttons.index", 5);
pref("kmeleon.toolband.&Zoom Buttons.size", 59);
pref("kmeleon.toolband.&Zoom Buttons.visibility", true);