
#include "nsISupports.idl"
#include "nsIDOMWindow.idl"
interface nsISimpleEnumerator; 
[scriptable, uuid(3d8ce8f0-5214-11db-b0de-0800200c9a66)] 

interface nsIJSBridge : nsISupports 
{ 
	const unsigned short      MENU_COMMAND       = 1;
	const unsigned short      MENU_POPUP     = 2;
	const unsigned short      MENU_INLINE          = 3;
	const unsigned short      MENU_PLUGIN = 4;
	const unsigned short      MENU_SEPARATOR = 5;

	void SetMenu(in string menu,in unsigned short type, in string label, in string command, in string before);
	void RebuildMenu(in string menu);

	void id(in nsIDOMWindow window, in string id);

	//void SendMessage(in string plugin, in string to, in string from, in long data1, inout long data2);
	//void test();

}; 

