#include "nsISupports.idl"
#include "nsIDOMWindow.idl"
#include "nsIWebBrowser.idl"
interface nsISimpleEnumerator; 
interface nsIArray;

[scriptable, uuid(3d8ce8f0-5214-11db-b0de-0800200c9a66)] 

interface kICmdList : nsISupports
{
	readonly attribute  unsigned long id;
	readonly attribute  string cmd;
	readonly attribute  string desc;
};

[scriptable, uuid(83910267-7670-4493-99c1-dd540a036ef2)] 

interface nsIJSBridge : nsISupports 
{ 
	const unsigned short      MENU_COMMAND       = 1;
	const unsigned short      MENU_POPUP     = 2;
	const unsigned short      MENU_INLINE          = 3;
	const unsigned short      MENU_PLUGIN = 4;
	const unsigned short      MENU_SEPARATOR = 5;

	const unsigned short      OPEN_NORMAL = 0;
	const unsigned short      OPEN_NEW = 1;
	const unsigned short      OPEN_BACKGROUND = 2;
	const unsigned short      OPEN_NEWTAB = 3;
	const unsigned short      OPEN_BACKGROUNDTAB = 4;
	const unsigned short      OPEN_CLONE = 16;

	void SetMenu(in string menu,in unsigned short type, in string label, in string command, in string before);
	void RebuildMenu(in string menu);

	void id(in nsIDOMWindow window, in string id);
	void SendMessage(in string plugin, in string to, in string from, in long data1, inout long data2);
	void GetCmdList(out unsigned long length, [array, size_is(length), retval] out kICmdList list);
	
	nsIWebBrowser Open(in string url, in unsigned short state);

}; 

