#Default Toolbar position for Phoenity

pref("kmeleon.toolband.GO.break", 0);
pref("kmeleon.toolband.GO.index", 8);
pref("kmeleon.toolband.GO.size", 59);
pref("kmeleon.toolband.GO.visibility", true);
pref("kmeleon.toolband.Layer/Window Buttons.break", 0);
pref("kmeleon.toolband.Layer/Window Buttons.index", 1);
pref("kmeleon.toolband.Layer/Window Buttons.size", 59);
pref("kmeleon.toolband.Layer/Window Buttons.visibility", true);
pref("kmeleon.toolband.Layers.visibility", true);
pref("kmeleon.toolband.Mail and News.break", 0);
pref("kmeleon.toolband.Mail and News.index", 4);
pref("kmeleon.toolband.Mail and News.size", 36);
pref("kmeleon.toolband.Mail and News.visibility", true);
pref("kmeleon.toolband.Main Bar.break", 1);
pref("kmeleon.toolband.Main Bar.index", 3);
pref("kmeleon.toolband.Main Bar.size", 197);
pref("kmeleon.toolband.Main Bar.visibility", true);
pref("kmeleon.toolband.Menu.break", 0);
pref("kmeleon.toolband.Menu.index", 0);
pref("kmeleon.toolband.Menu.size", 933);
pref("kmeleon.toolband.Menu.visibility", true);
pref("kmeleon.toolband.Privacy Bar.visibility", false);
pref("kmeleon.toolband.Search.break", 0);
pref("kmeleon.toolband.Search.index", 6);
pref("kmeleon.toolband.Search.size", 36);
pref("kmeleon.toolband.Search.visibility", true);
pref("kmeleon.toolband.Throbber.break", 0);
pref("kmeleon.toolband.Throbber.index", 2);
pref("kmeleon.toolband.Throbber.size", 28);
pref("kmeleon.toolband.Throbber.visibility", true);
pref("kmeleon.toolband.URL Bar.break", 0);
pref("kmeleon.toolband.URL Bar.index", 7);
pref("kmeleon.toolband.URL Bar.size", 536);
pref("kmeleon.toolband.URL Bar.visibility", true);
pref("kmeleon.toolband.Zoom.break", 0);
pref("kmeleon.toolband.Zoom.index", 5);
pref("kmeleon.toolband.Zoom.size", 59);
pref("kmeleon.toolband.Zoom.visibility", true);