//Default Toolbar position for Phoenity

pref("kmeleon.toolband.&Go Buttons.break", 0);
pref("kmeleon.toolband.&Go Buttons.index", 8);
pref("kmeleon.toolband.&Go Buttons.visibility", true);
pref("kmeleon.toolband.Mail/&News Buttons.break", 0);
pref("kmeleon.toolband.Mail/&News Buttons.index", 4);
pref("kmeleon.toolband.Mail/&News Buttons.visibility", true);
pref("kmeleon.toolband.&Main Bar.break", 1);
pref("kmeleon.toolband.&Main Bar.index", 3);
pref("kmeleon.toolband.&Main Bar.visibility", true);
pref("kmeleon.toolband.Menu.break", 0);
pref("kmeleon.toolband.Menu.index", 0);
pref("kmeleon.toolband.Menu.size", 1600);
pref("kmeleon.toolband.Menu.visibility", true);
pref("kmeleon.toolband.&Privacy Bar.break", 0);
pref("kmeleon.toolband.&Privacy Bar.index", 9);
pref("kmeleon.toolband.&Privacy Bar.visibility", false);
pref("kmeleon.toolband.&Search Buttons.break", 0);
pref("kmeleon.toolband.&Search Buttons.index", 6);
pref("kmeleon.toolband.&Search Buttons.visibility", true);
pref("kmeleon.toolband.Tab/&Window Buttons.break", 0);
pref("kmeleon.toolband.Tab/&Window Buttons.index", 1);
pref("kmeleon.toolband.Tab/&Window Buttons.visibility", true);
pref("kmeleon.toolband.Tabs.break", 1);
pref("kmeleon.toolband.Tabs.index", 10);
pref("kmeleon.toolband.Tabs.visibility", true);
pref("kmeleon.toolband.Throbber.break", 0);
pref("kmeleon.toolband.Throbber.index", 2);
pref("kmeleon.toolband.Throbber.visibility", true);
pref("kmeleon.toolband.URL Bar.break", 0);
pref("kmeleon.toolband.URL Bar.index", 7);
pref("kmeleon.toolband.URL Bar.size", 1600);
pref("kmeleon.toolband.URL Bar.visibility", true);
pref("kmeleon.toolband.&Zoom Buttons.break", 0);
pref("kmeleon.toolband.&Zoom Buttons.index", 5);
pref("kmeleon.toolband.&Zoom Buttons.visibility", true);